[package]
name = "stat"
version = "0.1.0"
edition = "2021"

[dependencies]
checksums = "0.9.1"
chrono = "0.4.40"
exitcode = "1.1.2"
filetime = "0.2.25"
log = "0.4.26"
phf = {version = "0.11.3", features = ["macros"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", features = ["preserve_order"]}
simple-logging = "2.0.2"

[profile.release]
panic = 'abort'
